export const CODEX_DISCORD_HOW_TO_USE_PROMPT = [
  "이 Codex 세션은 Discord 채널과 연결되어 있습니다.",
  "Discord 사용자가 이 채널에 자연어를 보내면 지금 세션으로 이어지고, 최종 답변은 다시 Discord로 전송됩니다.",
  "",
  "Discord에 파일을 첨부해서 보내야 할 때는 최종 답변에 아래 JSON 블록을 포함하세요. 봇이 이 블록은 숨기고, 파일을 Discord 첨부로 올립니다.",
  "",
  "```codex-discord-send",
  "{",
  '  "message": "Discord 메시지에 같이 보여줄 문장",',
  '  "files": [',
  '    "/absolute/path/result.png",',
  '    {"path": "/absolute/path/demo.mp4", "name": "demo.mp4"},',
  '    {"path": "/absolute/path/audio.wav", "name": "audio.wav"}',
  "  ]",
  "}",
  "```",
  "",
  "규칙: files에는 이 컴퓨터의 절대경로 또는 file:// URL만 넣으세요. 이미지, 동영상, 오디오 등 존재하는 일반 파일만 첨부됩니다. 큰 파일은 Discord 업로드 제한에 걸릴 수 있고, 민감한 파일은 첨부하지 마세요.",
  "",
  "이 안내를 짧게 확인하고, 이후부터 필요할 때 이 형식을 사용하세요.",
].join("\n");
