export const MAX_DISCORD_ATTACHMENT_BYTES = 10 * 1024 * 1024;
export const MAX_DISCORD_ATTACHMENT_LABEL = "10MiB";
export const MAX_DISCORD_ATTACHMENT_DISCORD_LABEL = "10MB";
export const MAX_DISCORD_FILES = 10;

